# -*- coding: utf-8 -*-
"""BEM Validation Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5FZV77-sZQDH-VRux30L6haeA9uT8K2
"""

import numpy as np

def calculate_propeller_thrust(theta_deg_start,theta_deg_end, R, R_root, c0,c1, RPM, V_c, N_b, a_w, cla0, alpha_l0_deg, N_elements=20):
    """
    Calculates the thrust coefficient (C_T) for a propeller using BEM theory.
    """
    # 1. Convert units and define globals
    Omega = RPM * (2 * np.pi / 60)       # Rotational speed [rad/s]       # Twist angle [rad]
    alpha_l0 = np.radians(alpha_l0_deg)  # Zero-lift angle of attack [rad]
    #cla = np.deg2rad(cla0)
    cla = cla0 * (180 / np.pi)


    # Climb velocity coefficient
    lambda_c = V_c / (Omega * R)

    # 2. Discretize the blade into N elements
    r_root_nd = R_root / R               # the wind start by %
    dr = (1.0 - r_root_nd) / N_elements  # each element %

    #  array each element
    r_array = np.linspace(r_root_nd + dr/2, 1.0 - dr/2, N_elements)

    c_array= np.linspace(c0,c1,N_elements) # un chord

    Teta_arr= np.linspace(np.deg2rad(theta_deg_start),np.deg2rad(theta_deg_end)  ,N_elements) #un angle


    # 3. Calculate solidity (sigma)
    # Since chord is constant in this validation case, sigma is constant


    total_CT = 0.0 # Initialize total thrust coefficient

    # 4. The Core Loop: Solve for each element
    for k in range(N_elements):
        r= r_array[k]
        c= c_array[k]
        sigma = (N_b * c) / (np.pi * R)

        theta= Teta_arr[k]



        A = (2 * r) / a_w
        B = (0.5 * sigma * cla * r) - (2 * r * lambda_c)
        C_const = -0.5 * sigma * cla * (r**2) * (theta + alpha_l0)

        # x = (-B + sqrt(B^2 - 4AC)) / 2A
        discriminant = B**2 - 4 * A * C_const

        if discriminant >= 0:
            lambda_val = (-B + np.sqrt(discriminant)) / (2 * A)
        else:
            lambda_val = 0

        # Calculate elemental thrust coefficient dC_T
        dCT = 0.5 * sigma * cla * (theta * r**2 - lambda_val * r + alpha_l0 * r**2) * dr


        total_CT += dCT

    return total_CT

if __name__ == "__main__":
    # --- TABLE 1: Global Parameters ---
    R = 1.829           # Radius [m]
    R_root = 0.178      # Root cut-off [m]
    c = 0.1524          # Chord [m]
    RPM = 600           # Rotational speed [RPM]
    V_c = 0.0           # Climb velocity [m/s]
    N_b = 3           # Number of blades
    a_w = 0.61            # Wake contraction ratio


    cla = 0.1096         #in Dgree  # Lift-curve slope [1/rad]
    alpha_l0 = 0.0     # Zero-lift angle of attack [deg]



    for j in [1,8,15]:
        print("Ct:",calculate_propeller_thrust(j,j, R, R_root, c,c, RPM, V_c, N_b, a_w, cla, alpha_l0))

"""<div style="background-color: #e3f2fd; padding: 15px; border-radius: 5px; border-left: 5px solid #1976d2;">
    <h3> Key Physics Assumptions</h3>
    <ul>
        <li><b>Climb Velocity (V_c = 0):</b> This represents a static test (e.g., holding brakes before takeoff). Aerodynamically, this is your <b>maximum thrust condition</b>, not a lower limit! Because the incoming speed is zero, the inflow angle ($\varphi$) is minimized, meaning your effective angle of attack ($\alpha$) is maximized.</li>
        <li><b>Wake Contraction (a_w = 0.61):</b> While real wake contraction changes with speed, your project uses a fixed empirical constant of 0.61 to simplify the 3D losses in the BEM equations. Keep this fixed for your analysis!</li>
    </ul>
</div>


"""

import numpy as np
from scipy.optimize import minimize

# 1. The Core Physics Engine (Your validated BEM code)
def calculate_propeller_thrust(theta_array_deg, c_array, R, R_root, RPM, V_c, N_b, a_w, cla0, alpha_l0_deg, N_elements=20):
    Omega = RPM * (2 * np.pi / 60)
    alpha_l0 = np.radians(alpha_l0_deg)
    cla = cla0 * (180 / np.pi)
    lambda_c = V_c / (Omega * R)

    r_root_nd = R_root / R
    dr = (1.0 - r_root_nd) / N_elements
    r_array = np.linspace(r_root_nd + dr/2, 1.0 - dr/2, N_elements)

    total_CT = 0.0

    for k in range(N_elements):
        r = r_array[k]
        c_local = c_array[k]
        theta = np.radians(theta_array_deg[k]) # Convert local twist to radians

        sigma = (N_b * c_local) / (np.pi * R)
        A = (2 * r) / a_w
        B = (0.5 * sigma * cla * r) - (2 * r * lambda_c)
        C_const = -0.5 * sigma * cla * (r**2) * (theta + alpha_l0)

        discriminant = B**2 - 4 * A * C_const
        if discriminant >= 0:
            lambda_val = (-B + np.sqrt(discriminant)) / (2 * A)
        else:
            lambda_val = 0

        dCT = 0.5 * sigma * cla * (theta * r**2 - lambda_val * r + alpha_l0 * r**2) * dr
        total_CT += dCT

    return total_CT

# 2. The Objective Function (What SciPy will try to minimize)
def objective_function(x, R, R_root, RPM, V_c, N_b, a_w, cla0, alpha_l0_deg, N_elements):
    # Unpack the guessed variables from SciPy
    c_root_guess, c_tip_guess, theta_root_guess, theta_tip_guess = x

    # Build the smooth linear arrays from the guesses
    c_array = np.linspace(c_root_guess, c_tip_guess, N_elements)
    theta_array = np.linspace(theta_root_guess, theta_tip_guess, N_elements)

    # Run the physics engine
    CT = calculate_propeller_thrust(theta_array, c_array, R, R_root, RPM, V_c, N_b, a_w, cla0, alpha_l0_deg, N_elements)

    # Note: SciPy ONLY minimizes. To maximize CT, we tell it to minimize negative CT!
    return -CT

# ==========================================
# PHASE 3: EXECUTE OPTIMIZATION
# ==========================================
if __name__ == "__main__":
    # --- Project Constraints ---
    R = 0.120           # Radius [m] [cite: 23]
    R_root = 0.030      # Root cut-off [m] [cite: 23]
    RPM = 10000         # Design point between 5,000-15,000 [cite: 23]
    V_c = 0.0           # Static condition [cite: 23]
    N_b = 2             # Number of blades [cite: 23]
    a_w = 0.61          # Wake contraction ratio
    N_elements = 20

    # --- Airfoil Data ---
    cla0 = 0.1          # XFLR5 slope [1/degree]
    alpha_l0_deg = 0.0  # Zero-lift angle [degree]

    # --- Set Up the Optimizer ---
    # Initial guess to start the algorithm: [c_root, c_tip, theta_root, theta_tip]
    initial_guess = [0.020, 0.015, 30.0, 15.0]

    # Absolute boundaries from your project brief [cite: 23]
    # format: (min, max) for each of the 4 variables
    bnds = (
        (0.001, 0.040),  # c_root limits [m]
        (0.001, 0.040),  # c_tip limits [m]
        (0.0, 90.0),     # theta_root limits [deg]
        (0.0, 90.0)      # theta_tip limits [deg]
    )

    # Run the SLSQP Optimization Algorithm
    print("Running optimization algorithm... Please wait...")
    result = minimize(
        objective_function,
        initial_guess,
        args=(R, R_root, RPM, V_c, N_b, a_w, cla0, alpha_l0_deg, N_elements),
        method='SLSQP',
        bounds=bnds
    )

    # --- Extract and Print Results ---
    opt_c_root, opt_c_tip, opt_theta_root, opt_theta_tip = result.x
    max_CT = -result.fun # Reverse the negative sign

    print("\n" + "="*45)
    print("🏆 OPTIMAL PROPELLER DESIGN FOUND 🏆")
    print("="*45)
    print(f"Maximized Thrust Coefficient (C_T): {max_CT:.5f}")
    print("\nOptimized Geometry:")
    print(f"Root Chord:  {opt_c_root*1000:.1f} mm")
    print(f"Tip Chord:   {opt_c_tip*1000:.1f} mm")
    print(f"Root Twist:  {opt_theta_root:.1f} degrees")
    print(f"Tip Twist:   {opt_theta_tip:.1f} degrees")
    print("="*45)